### ISSUE TITLE
How do you add global values/Call global methods?

### ISSUE THREAD

**Issue by bbuck** [alexeyco/binder#1]
Hey, this looks great! Much simpler than the API I've created for simplifying working with `gopher-lua`. 

I was curious though, I can't seem to find a way to assign variables or access existing variables (like, for example, wanted to reassign the package loaders or load paths, etc..), am I just missing something?

**Comment by alexeyco** [comment]
I have no idea, bro ((

**Comment by leonidboykov** [comment]
Hi, maybe it is a good idea to export Lua `state` from Binder struct? So we may access GetGlobal and other methods. Or add some options to assign our own state at Binder initialization.
